name: jobify-mern-app

services:
  mongo:
    image: mongo:7.0.12
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - mern_app

  api: 
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./server/.env
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - mern_app
    depends_on:
      - mongo

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - mern_app
    depends_on:
      - api
    
  caddy:
    image: caddy:2-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - mern_app
    depends_on:
      - frontend
      - api

volumes:
  mongo_data:
  caddy_data:
  caddy_config:

networks:
  mern_app:
    driver: bridge
